import React, { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone';
import axios from 'axios';
import {
  Box,
  Paper,
  Typography,
  Button,
  LinearProgress,
  Alert,
  Chip,
  Divider,
  Grid
} from '@mui/material';
import {
  CloudUpload as UploadIcon,
  CheckCircle as CheckIcon,
  Error as ErrorIcon,
  Refresh as RefreshIcon,
  Speed as SpeedIcon,
  AccessTime as TimeIcon,
  GraphicEq as WaveIcon,
  Memory as ChipIcon
} from '@mui/icons-material';

import ConfidenceChart from '../components/ConfidenceChart';
import AudioWaveform from '../components/AudioWaveform';
import ProbabilityGauge from '../components/ProbabilityGauge';
import WarningBanner from '../components/WarningBanner';
import RiskSignals from '../components/RiskSignals';
import AudioGraph from '../components/AudioGraph';

const API_URL = process.env.REACT_APP_API_URL !== undefined
  ? process.env.REACT_APP_API_URL
  : (process.env.NODE_ENV === 'production' ? '' : 'http://localhost:8000');

/**
 * UploadPage Component
 * Handles audio file upload and displays comprehensive detection dashboard
 */
const UploadPage = () => {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [selectedChunk, setSelectedChunk] = useState(null);

  /**
   * Handle file drop
   */
  const onDrop = useCallback((acceptedFiles) => {
    if (acceptedFiles.length > 0) {
      const selectedFile = acceptedFiles[0];

      // Validate file type
      const validTypes = ['audio/wav', 'audio/mpeg', 'audio/mp3', 'audio/ogg', 'audio/flac'];
      if (!validTypes.includes(selectedFile.type)) {
        setError('Please upload a valid audio file (WAV, MP3, OGG, FLAC)');
        return;
      }

      setFile(selectedFile);
      setError(null);
      setResult(null);
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'audio/*': ['.wav', '.mp3', '.ogg', '.flac']
    },
    multiple: false
  });

  /**
   * Upload and process file
   */
  const handleUpload = async () => {
    if (!file) return;

    setUploading(true);
    setError(null);

    const formData = new FormData();
    formData.append('file', file);

    try {
      const response = await axios.post(`${API_URL}/upload`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        },
        onUploadProgress: (progressEvent) => {
          const percentCompleted = Math.round(
            (progressEvent.loaded * 100) / progressEvent.total
          );
          console.log(`Upload progress: ${percentCompleted}%`);
        }
      });

      setResult(response.data);
      if (response.data.chunks?.length > 0) {
        setSelectedChunk(response.data.chunks[0]);
      }
    } catch (err) {
      setError(
        err.response?.data?.detail ||
        'Error processing audio file. Please try again.'
      );
    } finally {
      setUploading(false);
    }
  };

  /**
   * Reset form
   */
  const handleReset = () => {
    setFile(null);
    setResult(null);
    setError(null);
    setSelectedChunk(null);
  };

  /**
   * Get status color
   */
  const getStatusColor = (isAI) => {
    return isAI ? '#ef4444' : '#22c55e';
  };

  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        Upload Audio for AI Detection
      </Typography>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
        Upload an audio file to analyze whether it was generated by AI or recorded from a human voice.
      </Typography>

      {/* Upload area */}
      {!result && (
        <Paper elevation={0} sx={{ p: 3, bgcolor: '#1e293b', borderRadius: 2 }}>
          <div
            {...getRootProps()}
            className={`dropzone ${isDragActive ? 'active' : ''}`}
          >
            <input {...getInputProps()} />
            <UploadIcon sx={{ fontSize: 48, color: '#3b82f6', mb: 2 }} />
            {isDragActive ? (
              <Typography>Drop the audio file here...</Typography>
            ) : (
              <>
                <Typography variant="h6" gutterBottom>
                  Drag & drop an audio file here
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  or click to select a file (WAV, MP3, OGG, FLAC)
                </Typography>
              </>
            )}
          </div>

          {file && (
            <Box sx={{ mt: 3 }}>
              <Typography variant="subtitle2" gutterBottom>
                Selected file:
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                <Typography>{file.name}</Typography>
                <Typography variant="body2" color="text.secondary">
                  ({(file.size / 1024 / 1024).toFixed(2)} MB)
                </Typography>
              </Box>

              {uploading ? (
                <Box sx={{ mt: 2 }}>
                  <LinearProgress />
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    Processing audio...
                  </Typography>
                </Box>
              ) : (
                <Box sx={{ mt: 2, display: 'flex', gap: 2 }}>
                  <Button
                    variant="contained"
                    onClick={handleUpload}
                    startIcon={<CheckIcon />}
                  >
                    Analyze Audio
                  </Button>
                  <Button
                    variant="outlined"
                    onClick={handleReset}
                    startIcon={<RefreshIcon />}
                  >
                    Clear
                  </Button>
                </Box>
              )}
            </Box>
          )}

          {error && (
            <Alert severity="error" sx={{ mt: 3 }} icon={<ErrorIcon />}>
              {error}
            </Alert>
          )}
        </Paper>
      )}

      {/* ===== RESULTS DASHBOARD ===== */}
      {result && (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>

          {/* 1. Warning Banner — full width */}
          <WarningBanner
            message={result.warning_message}
            level={result.warning_level}
          />

          {/* 2. Probability Gauge + Quick Stats — side by side */}
          <Grid container spacing={3}>
            {/* Gauge */}
            <Grid item xs={12} md={5}>
              <Paper elevation={0} sx={{
                p: 3,
                bgcolor: '#1e293b',
                borderRadius: 2,
                height: '100%',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center'
              }}>
                <Typography variant="h6" gutterBottom>Detection Result</Typography>
                <ProbabilityGauge
                  aiProbability={result.overall_prediction?.ai_probability || 0}
                  humanProbability={result.overall_prediction?.human_probability || 0}
                  size={220}
                />
              </Paper>
            </Grid>

            {/* Quick Stats */}
            <Grid item xs={12} md={7}>
              <Paper elevation={0} sx={{ p: 3, bgcolor: '#1e293b', borderRadius: 2, height: '100%' }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                  <Typography variant="h6">Analysis Summary</Typography>
                  <Button
                    variant="outlined"
                    size="small"
                    onClick={handleReset}
                    startIcon={<RefreshIcon />}
                  >
                    Analyze Another
                  </Button>
                </Box>

                {/* Verdict */}
                <Box sx={{
                  p: 2.5,
                  bgcolor: '#0f172a',
                  borderRadius: 2,
                  border: `2px solid ${getStatusColor(result.overall_prediction?.is_ai_generated)}`,
                  mb: 2.5
                }}>
                  <Typography variant="h5" sx={{
                    color: getStatusColor(result.overall_prediction?.is_ai_generated),
                    fontWeight: 700
                  }}>
                    {result.overall_prediction?.is_ai_generated ? '🤖 AI-Generated Audio' : '👤 Human Voice Detected'}
                  </Typography>
                </Box>

                {/* Stat chips grid */}
                <Grid container spacing={1.5}>
                  <Grid item xs={6}>
                    <Box sx={{ p: 1.5, bgcolor: '#0f172a', borderRadius: 1.5, display: 'flex', alignItems: 'center', gap: 1 }}>
                      <SpeedIcon sx={{ color: '#3b82f6', fontSize: 20 }} />
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1 }}>Confidence</Typography>
                        <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                          {Math.round(result.overall_prediction?.confidence * 100)}%
                        </Typography>
                      </Box>
                    </Box>
                  </Grid>
                  <Grid item xs={6}>
                    <Box sx={{ p: 1.5, bgcolor: '#0f172a', borderRadius: 1.5, display: 'flex', alignItems: 'center', gap: 1 }}>
                      <TimeIcon sx={{ color: '#8b5cf6', fontSize: 20 }} />
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1 }}>Duration</Typography>
                        <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                          {result.duration?.toFixed(2)}s
                        </Typography>
                      </Box>
                    </Box>
                  </Grid>
                  <Grid item xs={6}>
                    <Box sx={{ p: 1.5, bgcolor: '#0f172a', borderRadius: 1.5, display: 'flex', alignItems: 'center', gap: 1 }}>
                      <WaveIcon sx={{ color: '#f59e0b', fontSize: 20 }} />
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1 }}>Sample Rate</Typography>
                        <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                          {result.sample_rate ? `${(result.sample_rate / 1000).toFixed(1)} kHz` : 'N/A'}
                        </Typography>
                      </Box>
                    </Box>
                  </Grid>
                  <Grid item xs={6}>
                    <Box sx={{ p: 1.5, bgcolor: '#0f172a', borderRadius: 1.5, display: 'flex', alignItems: 'center', gap: 1 }}>
                      <ChipIcon sx={{ color: '#22c55e', fontSize: 20 }} />
                      <Box>
                        <Typography variant="caption" color="text.secondary" sx={{ display: 'block', lineHeight: 1 }}>Segments</Typography>
                        <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
                          {result.num_chunks} analyzed
                        </Typography>
                      </Box>
                    </Box>
                  </Grid>
                </Grid>
              </Paper>
            </Grid>
          </Grid>

          {/* 3. Audio Graph — full width waveform */}
          <Paper elevation={0} sx={{ p: 3, bgcolor: '#1e293b', borderRadius: 2 }}>
            <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              📊 Audio Waveform Analysis
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Waveform colored by detection result — <span style={{ color: '#ef4444' }}>red regions</span> indicate AI-generated audio, <span style={{ color: '#22c55e' }}>green regions</span> indicate human voice.
            </Typography>
            <AudioGraph
              waveform={result.waveform || []}
              chunks={result.chunks || []}
              duration={result.duration || 0}
            />
          </Paper>

          {/* 4. Risk Signals */}
          <RiskSignals signals={result.risk_signals || []} />

          {/* 5. Confidence chart by chunk */}
          <Paper elevation={0} sx={{ p: 3, bgcolor: '#1e293b', borderRadius: 2 }}>
            <Typography variant="h6" gutterBottom>
              📈 Detection Confidence by Segment
            </Typography>
            <ConfidenceChart data={result.chunks || []} height={250} />
          </Paper>

          {/* 6. Detailed segment cards */}
          <Paper elevation={0} sx={{ p: 3, bgcolor: '#1e293b', borderRadius: 2 }}>
            <Typography variant="h6" gutterBottom>
              🔍 Detailed Segment Analysis
            </Typography>

            <Box sx={{ display: 'flex', gap: 2, overflowX: 'auto', pb: 2 }}>
              {result.chunks?.map((chunk, index) => (
                <Box
                  key={index}
                  onClick={() => setSelectedChunk(chunk)}
                  sx={{
                    minWidth: 200,
                    p: 2,
                    bgcolor: selectedChunk?.index === chunk.index ? '#334155' : '#0f172a',
                    borderRadius: 2,
                    cursor: 'pointer',
                    border: `2px solid ${chunk.prediction?.is_ai_generated ? '#ef4444' : '#22c55e'}`,
                    '&:hover': {
                      bgcolor: '#334155'
                    }
                  }}
                >
                  <Typography variant="subtitle2">
                    Segment {index + 1}
                  </Typography>
                  <Typography variant="caption" display="block" color="text.secondary">
                    {chunk.start_time?.toFixed(1)}s - {chunk.end_time?.toFixed(1)}s
                  </Typography>
                  <Box sx={{ mt: 1 }}>
                    <Typography variant="body2" sx={{
                      color: chunk.prediction?.is_ai_generated ? '#ef4444' : '#22c55e'
                    }}>
                      {chunk.prediction?.is_ai_generated ? '🤖 AI' : '👤 Human'}: {Math.round(chunk.prediction?.ai_probability * 100)}%
                    </Typography>
                  </Box>
                </Box>
              ))}
            </Box>

            {/* Selected chunk waveform */}
            {selectedChunk && (
              <Box sx={{ mt: 3 }}>
                <Divider sx={{ mb: 3 }} />
                <Typography variant="subtitle2" gutterBottom>
                  Waveform - Segment {selectedChunk.index + 1}
                </Typography>
                <AudioWaveform
                  audioData={selectedChunk.waveform}
                  width={600}
                  height={120}
                  color={selectedChunk.prediction?.is_ai_generated ? '#ef4444' : '#22c55e'}
                />
              </Box>
            )}
          </Paper>
        </Box>
      )}
    </Box>
  );
};

export default UploadPage;